apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploymentName
  labels:
    owner: DorinLupu
spec:
  selector:
    matchLabels:
      app: podName
  template:
    metadata:
      labels:
        app: podName
    spec:
      containers:
      - name: containerName
        image: nginx:latest
        ports:
        - containerPort: 80
