apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploymentname-autoscaling
  labels:
    owner: DorinLupu
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sas
  template:
    metadata:
      labels:
        app: sas
    spec:
      containers:
      - name: containername
        image: httpd:latest
        ports:
        - containerPort: 80

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: my-autoscaling
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: deploymentname-autoscaling
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50

