apiVersion: v1
kind: Pod
metadata:
  name: my-web
  labels:
    name: myapp
spec:
  containers:
  - name: container-app
    image: nginx:latest
    ports:
      - containerPort: 80

  - name: container-api
    image: httpd:latest
    ports:
      - containerPort: 8080
