apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploymentname
  labels:
    owner: DorinLupu
spec:
  selector:
    matchLabels:
      app: podname
  template:
    metadata:
      labels:
        app: podname    # Service will look for those PODS Labels!!!
    spec:
      containers:
      - name: containername
        image: dorin1025/k8sphpapp2:latest
        ports:
        - containerPort: 80

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: myapp
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: deploymentname
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50

---
apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels:
     owner: DorinLupu
     env  : prod
spec:
  selector:
    app: podname  # Selecting PODS with those Labels
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer

